#备份配置文件
server:
 port: 9001
spring:
 application:
  name: tensquare-base #指定服务名
 data:
    mongodb:
     host: 47.107.183.79
     database: spitdb
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.107.183.79:3306/tensquare_base?characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456
 jpa:
  database: MySQL
  show-sql: true
  generate-ddl: true
 rabbitmq:
  host: 47.107.183.79
  password: shawn
  username: shawn
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
base:
  name: myBaseUpdate