server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.183.79:3306/tensquare_qa?useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 47.107.183.79
    password: shawn
    username: shawn
jwt:
 config:
  key: shawn
  ttl: 3600000
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true


