server:
  port: 9007
spring:
  application:
    name: tensquare_search
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
  rabbitmq:
   host: 47.107.183.79
   password: shawn
   username: shawn