server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.183.79:3306/tensquare_user?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 47.107.183.79
    password: shawn
    username: shawn
  redis:
    host: 47.107.183.79
jwt:
 config:
  key: shawn
  ttl: 3600000
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
user:
  name: myUserUpdate
