server:
  port: 9013
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/LuckyShawn/tensquare-config.git
  rabbitmq:
    host: 47.107.183.79
    username: shawn
    password: shawn
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh


